### ISSUE TITLE
Chef 14 Support

### ISSUE THREAD

**Issue by WheresAlice** [sous-chefs/control_groups#14]
### Cookbook version
0.1.6

### Chef-client version
14.8.12

### Platform Details
CentOS 7

### Scenario:
The latest release does not support Chef 14, however I notice there are subsequent commits which add this in.  Using the version of the cookbook in the master branch works.  So it looks like it just needs a new release making.

### Steps to Reproduce:
Add any `control_groups_entry` entry to a recipe

### Expected Result:
chef-client run converges

### Actual Result:

```
================================================================================
           Error executing action `create` on resource 'control_groups_entry[docker]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `platform_family' for #<Chef::Node::Attribute:0x0000000004398010>

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/control_groups/recipes/default.rb:1:in `from_file'
           /tmp/kitchen/cache/cookbooks/control_groups/providers/entry.rb:7:in `block in class_from_file'
```

**Comment by damacus** [comment]
Hey @WheresAlice thanks for opening an issue! 

we've recently taken ownership of `control_groups` and it needs a *big* overhaul. If you want to drop by the #sous-chefs channel we can probably figure out how to get this done. 

We have a meeting tonight which I'll bring this up in 👍

**Comment by tas50** [comment]
@WheresAlice We just merged in a big rewrite of the resources. I'm going to close this out at this point. Let me know if you're still seeing issues though.
